# ── Single source of truth for all tickers ────────────────────
# All 3 fetch scripts import from here.
# To add/remove tickers, edit only this file.

DJIA_TICKERS = [
    "AAPL","AMGN","AXP","BA","CAT","CRM","CSCO","CVX","DIS","DOW",
    "GS","HD","HON","IBM","INTC","JNJ","JPM","KO","MCD","MMM",
    "MRK","MSFT","NKE","PG","TRV","UNH","V","VZ","WMT","SHW"
]

# S&P 500
SP500_TICKERS = [
    "A","AAL","AAP","AAPL","ABBV","ABT","ACN","ADBE","ADI","ADM",
    "ADP","ADSK","AEE","AEP","AES","AFL","AIG","AIZ","AJG","AKAM",
    "ALB","ALGN","ALK","ALL","ALLE","AMAT","AMCR","AMD","AME","AMGN",
    "AMP","AMT","AMZN","ANET","AON","AOS","APA","APD","APH","APTV",
    "ARE","ATO","AVB","AVGO","AVY","AWK","AXP","AZO","BA","BAC",
    "BALL","BAX","BBWI","BBY","BDX","BEN","BF-B","BG","BIIB","BK",
    "BKNG","BKR","BLK","BMY","BR","BRK-B","BRO","BSX","BWA","BX",
    "C","CAG","CAH","CARR","CAT","CB","CBOE","CBRE","CCI","CCL",
    "CDNS","CDW","CE","CF","CFG","CHD","CHRW","CHTR","CI","CINF",
    "CL","CLX","CMA","CMCSA","CME","CMG","CMI","CMS","CNC","CNP",
    "COF","COO","COP","COST","CPB","CPRT","CPT","CRL","CRM","CSCO",
    "CSGP","CSX","CTAS","CTLT","CTRA","CTSH","CTVA","CVS","CVX","CZR",
    "D","DAL","DD","DE","DFS","DG","DGX","DHI","DHR","DIS",
    "DISH","DLR","DLTR","DOV","DOW","DPZ","DRE","DRI","DTE","DUK",
    "DVA","DVN","DXC","DXCM","EA","EBAY","ECL","ED","EFX","EG",
    "EIX","EL","EMN","EMR","ENPH","EOG","EPAM","EQIX","EQR","EQT",
    "ES","ESS","ETN","ETR","ETSY","EVRG","EW","EXC","EXPD","EXPE",
    "EXR","F","FANG","FAST","FCX","FDS","FDX","FE","FFIV","FIS",
    "FISV","FITB","FLT","FMC","FOX","FOXA","FRT","FTNT","FTV","GD",
    "GE","GEHC","GEN","GILD","GIS","GL","GLW","GM","GOOG","GOOGL",
    "GPC","GPN","GRMN","GS","GWW","HAL","HAS","HBAN","HCA","HD",
    "HES","HIG","HII","HLT","HOLX","HON","HPE","HPQ","HRL","HSIC",
    "HST","HSY","HUBB","HUM","HWM","IBM","ICE","IDXX","IEX","IFF",
    "ILMN","INCY","INTC","INTU","INVH","IP","IPG","IQV","IR","IRM",
    "ISRG","IT","ITW","IVZ","J","JBHT","JCI","JKHY","JNJ","JNPR",
    "JPM","K","KDP","KEY","KEYS","KHC","KIM","KLAC","KMB","KMI",
    "KMX","KO","KR","L","LDOS","LEN","LH","LHX","LIN","LKQ",
    "LLY","LMT","LNT","LOW","LRCX","LULU","LUV","LVS","LW","LYB",
    "LYV","MA","MAA","MAR","MAS","MCD","MCHP","MCK","MCO","MDLZ",
    "MDT","MET","META","MGM","MHK","MKC","MKTX","MLM","MMC","MMM",
    "MNST","MO","MOH","MOS","MPC","MPWR","MRK","MRNA","MRO","MS",
    "MSCI","MSFT","MSI","MTB","MTD","MU","NCLH","NDAQ","NEE","NEM",
    "NFLX","NI","NKE","NOC","NOW","NRG","NSC","NTAP","NTRS","NUE",
    "NVDA","NVR","NWL","NWS","NWSA","NXPI","O","ODFL","OKE","OMC",
    "ON","ORCL","ORLY","OXY","PARA","PAYC","PAYX","PCAR","PCG","PEAK",
    "PEG","PEP","PFE","PFG","PG","PGR","PH","PHM","PKG","PLD",
    "PM","PNC","PNR","PNW","POOL","PPG","PPL","PRU","PSA","PSX",
    "PTC","PWR","PYPL","QCOM","QRVO","RCL","RE","REG","REGN","RF",
    "RJF","RL","RMD","ROK","ROL","ROP","ROST","RSG","RTX","SBAC",
    "SBUX","SCHW","SHW","SJM","SLB","SNA","SNPS","SO","SPG","SPGI",
    "SRE","STE","STT","STX","STZ","SWK","SWKS","SYF","SYK","SYY",
    "T","TAP","TDG","TDY","TECH","TEL","TER","TFC","TFX","TGT",
    "TJX","TMO","TMUS","TPR","TRGP","TRMB","TROW","TRV","TSCO","TSLA",
    "TSN","TT","TTWO","TXN","TYL","UAL","UDR","UHS","UNH","UNP",
    "UPS","URI","USB","V","VFC","VICI","VLO","VMC","VNO","VRSK",
    "VRSN","VRTX","VTR","VTRS","VZ","WAB","WAT","WBA","WBD","WDC",
    "WEC","WELL","WFC","WHR","WM","WMB","WMT","WRB","WRK","WST",
    "WTW","WY","WYNN","XEL","XOM","XRAY","XYL","YUM","ZBH","ZBRA",
    "ZION","ZTS"
]

# Combined company name lookup
COMPANY_NAMES = {
    "A":"Agilent Technologies","AAL":"American Airlines","AAP":"Advance Auto Parts",
    "AAPL":"Apple","ABBV":"AbbVie","ABT":"Abbott","ACN":"Accenture",
    "ADBE":"Adobe","ADI":"Analog Devices","ADM":"Archer-Daniels-Midland",
    "ADP":"Automatic Data Processing","ADSK":"Autodesk","AEE":"Ameren",
    "AEP":"American Electric Power","AES":"AES Corp","AFL":"Aflac",
    "AIG":"AIG","AIZ":"Assurant","AJG":"Arthur J. Gallagher",
    "AKAM":"Akamai","ALB":"Albemarle","ALGN":"Align Technology",
    "ALK":"Alaska Air","ALL":"Allstate","ALLE":"Allegion",
    "AMAT":"Applied Materials","AMCR":"Amcor","AMD":"AMD",
    "AME":"AMETEK","AMGN":"Amgen","AMP":"Ameriprise Financial",
    "AMT":"American Tower","AMZN":"Amazon","ANET":"Arista Networks",
    "AON":"Aon","AOS":"A.O. Smith","APA":"APA Corp",
    "APD":"Air Products","APH":"Amphenol","APTV":"Aptiv",
    "ARE":"Alexandria Real Estate","ATO":"Atmos Energy","AVB":"AvalonBay",
    "AVGO":"Broadcom","AVY":"Avery Dennison","AWK":"American Water Works",
    "AXP":"American Express","AZO":"AutoZone","BA":"Boeing",
    "BAC":"Bank of America","BALL":"Ball Corp","BAX":"Baxter",
    "BBWI":"Bath & Body Works","BBY":"Best Buy","BDX":"Becton Dickinson",
    "BEN":"Franklin Resources","BF-B":"Brown-Forman","BG":"Bunge",
    "BIIB":"Biogen","BK":"BNY Mellon","BKNG":"Booking Holdings",
    "BKR":"Baker Hughes","BLK":"BlackRock","BMY":"Bristol-Myers Squibb",
    "BR":"Broadridge","BRK-B":"Berkshire Hathaway","BRO":"Brown & Brown",
    "BSX":"Boston Scientific","BWA":"BorgWarner","BX":"Blackstone",
    "C":"Citigroup","CAG":"Conagra Brands","CAH":"Cardinal Health",
    "CARR":"Carrier Global","CAT":"Caterpillar","CB":"Chubb",
    "CBOE":"Cboe Global Markets","CBRE":"CBRE Group","CCI":"Crown Castle",
    "CCL":"Carnival","CDNS":"Cadence Design","CDW":"CDW Corp",
    "CE":"Celanese","CF":"CF Industries","CFG":"Citizens Financial",
    "CHD":"Church & Dwight","CHRW":"C.H. Robinson","CHTR":"Charter Communications",
    "CI":"Cigna","CINF":"Cincinnati Financial","CL":"Colgate-Palmolive",
    "CLX":"Clorox","CMA":"Comerica","CMCSA":"Comcast",
    "CME":"CME Group","CMG":"Chipotle","CMI":"Cummins",
    "CMS":"CMS Energy","CNC":"Centene","CNP":"CenterPoint Energy",
    "COF":"Capital One","COO":"Cooper Companies","COP":"ConocoPhillips",
    "COST":"Costco","CPB":"Campbell Soup","CPRT":"Copart",
    "CPT":"Camden Property","CRL":"Charles River Labs","CRM":"Salesforce",
    "CSCO":"Cisco","CSGP":"CoStar Group","CSX":"CSX Corp",
    "CTAS":"Cintas","CTLT":"Catalent","CTRA":"Coterra Energy",
    "CTSH":"Cognizant","CTVA":"Corteva","CVS":"CVS Health",
    "CVX":"Chevron","CZR":"Caesars Entertainment","D":"Dominion Energy",
    "DAL":"Delta Air Lines","DD":"DuPont","DE":"Deere & Co",
    "DFS":"Discover Financial","DG":"Dollar General","DGX":"Quest Diagnostics",
    "DHI":"D.R. Horton","DHR":"Danaher","DIS":"Disney",
    "DISH":"Dish Network","DLR":"Digital Realty","DLTR":"Dollar Tree",
    "DOV":"Dover","DOW":"Dow Inc","DPZ":"Domino's Pizza",
    "DRE":"Duke Realty","DRI":"Darden Restaurants","DTE":"DTE Energy",
    "DUK":"Duke Energy","DVA":"DaVita","DVN":"Devon Energy",
    "DXC":"DXC Technology","DXCM":"Dexcom","EA":"Electronic Arts",
    "EBAY":"eBay","ECL":"Ecolab","ED":"Consolidated Edison",
    "EFX":"Equifax","EG":"Everest Group","EIX":"Edison International",
    "EL":"Estee Lauder","EMN":"Eastman Chemical","EMR":"Emerson Electric",
    "ENPH":"Enphase Energy","EOG":"EOG Resources","EPAM":"EPAM Systems",
    "EQIX":"Equinix","EQR":"Equity Residential","EQT":"EQT Corp",
    "ES":"Eversource Energy","ESS":"Essex Property","ETN":"Eaton",
    "ETR":"Entergy","ETSY":"Etsy","EVRG":"Evergy",
    "EW":"Edwards Lifesciences","EXC":"Exelon","EXPD":"Expeditors Intl",
    "EXPE":"Expedia","EXR":"Extra Space Storage","F":"Ford",
    "FANG":"Diamondback Energy","FAST":"Fastenal","FCX":"Freeport-McMoRan",
    "FDS":"FactSet Research","FDX":"FedEx","FE":"FirstEnergy",
    "FFIV":"F5 Networks","FIS":"Fidelity National Info","FISV":"Fiserv",
    "FITB":"Fifth Third Bancorp","FLT":"Fleetcor Technologies","FMC":"FMC Corp",
    "FOX":"Fox Corp B","FOXA":"Fox Corp A","FRT":"Federal Realty",
    "FTNT":"Fortinet","FTV":"Fortive","GD":"General Dynamics",
    "GE":"GE Aerospace","GEHC":"GE HealthCare","GEN":"Gen Digital",
    "GILD":"Gilead Sciences","GIS":"General Mills","GL":"Globe Life",
    "GLW":"Corning","GM":"General Motors","GOOG":"Alphabet C",
    "GOOGL":"Alphabet A","GPC":"Genuine Parts","GPN":"Global Payments",
    "GRMN":"Garmin","GS":"Goldman Sachs","GWW":"W.W. Grainger",
    "HAL":"Halliburton","HAS":"Hasbro","HBAN":"Huntington Bancshares",
    "HCA":"HCA Healthcare","HD":"Home Depot","HES":"Hess Corp",
    "HIG":"Hartford Financial","HII":"Huntington Ingalls","HLT":"Hilton",
    "HOLX":"Hologic","HON":"Honeywell","HPE":"HP Enterprise",
    "HPQ":"HP Inc","HRL":"Hormel Foods","HSIC":"Henry Schein",
    "HST":"Host Hotels","HSY":"Hershey","HUBB":"Hubbell",
    "HUM":"Humana","HWM":"Howmet Aerospace","IBM":"IBM",
    "ICE":"Intercontinental Exchange","IDXX":"IDEXX Laboratories","IEX":"IDEX Corp",
    "IFF":"Intl Flavors & Fragrances","ILMN":"Illumina","INCY":"Incyte",
    "INTC":"Intel","INTU":"Intuit","INVH":"Invitation Homes",
    "IP":"International Paper","IPG":"Interpublic Group","IQV":"IQVIA",
    "IR":"Ingersoll Rand","IRM":"Iron Mountain","ISRG":"Intuitive Surgical",
    "IT":"Gartner","ITW":"Illinois Tool Works","IVZ":"Invesco",
    "J":"Jacobs Solutions","JBHT":"J.B. Hunt Transport","JCI":"Johnson Controls",
    "JKHY":"Jack Henry & Associates","JNJ":"Johnson & Johnson","JNPR":"Juniper Networks",
    "JPM":"JPMorgan Chase","K":"Kellanova","KDP":"Keurig Dr Pepper",
    "KEY":"KeyCorp","KEYS":"Keysight Technologies","KHC":"Kraft Heinz",
    "KIM":"Kimco Realty","KLAC":"KLA Corp","KMB":"Kimberly-Clark",
    "KMI":"Kinder Morgan","KMX":"CarMax","KO":"Coca-Cola",
    "KR":"Kroger","L":"Loews","LDOS":"Leidos",
    "LEN":"Lennar","LH":"Labcorp","LHX":"L3Harris Technologies",
    "LIN":"Linde","LKQ":"LKQ Corp","LLY":"Eli Lilly",
    "LMT":"Lockheed Martin","LNT":"Alliant Energy","LOW":"Lowe's",
    "LRCX":"Lam Research","LULU":"Lululemon","LUV":"Southwest Airlines",
    "LVS":"Las Vegas Sands","LW":"Lamb Weston","LYB":"LyondellBasell",
    "LYV":"Live Nation","MA":"Mastercard","MAA":"Mid-America Apartment",
    "MAR":"Marriott","MAS":"Masco","MCD":"McDonald's",
    "MCHP":"Microchip Technology","MCK":"McKesson","MCO":"Moody's",
    "MDLZ":"Mondelez","MDT":"Medtronic","MET":"MetLife",
    "META":"Meta","MGM":"MGM Resorts","MHK":"Mohawk Industries",
    "MKC":"McCormick","MKTX":"MarketAxess","MLM":"Martin Marietta",
    "MMC":"Marsh & McLennan","MMM":"3M","MNST":"Monster Beverage",
    "MO":"Altria","MOH":"Molina Healthcare","MOS":"Mosaic",
    "MPC":"Marathon Petroleum","MPWR":"Monolithic Power","MRK":"Merck",
    "MRNA":"Moderna","MRO":"Marathon Oil","MS":"Morgan Stanley",
    "MSCI":"MSCI Inc","MSFT":"Microsoft","MSI":"Motorola Solutions",
    "MTB":"M&T Bank","MTD":"Mettler-Toledo","MU":"Micron Technology",
    "NCLH":"Norwegian Cruise Line","NDAQ":"Nasdaq","NEE":"NextEra Energy",
    "NEM":"Newmont","NFLX":"Netflix","NI":"NiSource",
    "NKE":"Nike","NOC":"Northrop Grumman","NOW":"ServiceNow",
    "NRG":"NRG Energy","NSC":"Norfolk Southern","NTAP":"NetApp",
    "NTRS":"Northern Trust","NUE":"Nucor","NVDA":"Nvidia",
    "NVR":"NVR Inc","NWL":"Newell Brands","NWS":"News Corp B",
    "NWSA":"News Corp A","NXPI":"NXP Semiconductors","O":"Realty Income",
    "ODFL":"Old Dominion Freight","OKE":"ONEOK","OMC":"Omnicom",
    "ON":"ON Semiconductor","ORCL":"Oracle","ORLY":"O'Reilly Automotive",
    "OXY":"Occidental Petroleum","PARA":"Paramount Global","PAYC":"Paycom",
    "PAYX":"Paychex","PCAR":"PACCAR","PCG":"PG&E",
    "PEAK":"Healthpeak Properties","PEG":"Public Service Enterprise","PEP":"PepsiCo",
    "PFE":"Pfizer","PFG":"Principal Financial","PG":"Procter & Gamble",
    "PGR":"Progressive","PH":"Parker Hannifin","PHM":"PulteGroup",
    "PKG":"Packaging Corp","PLD":"Prologis","PM":"Philip Morris",
    "PNC":"PNC Financial","PNR":"Pentair","PNW":"Pinnacle West",
    "POOL":"Pool Corp","PPG":"PPG Industries","PPL":"PPL Corp",
    "PRU":"Prudential Financial","PSA":"Public Storage","PSX":"Phillips 66",
    "PTC":"PTC Inc","PWR":"Quanta Services","PYPL":"PayPal",
    "QCOM":"Qualcomm","QRVO":"Qorvo","RCL":"Royal Caribbean",
    "RE":"Everest Re","REG":"Regency Centers","REGN":"Regeneron",
    "RF":"Regions Financial","RJF":"Raymond James","RL":"Ralph Lauren",
    "RMD":"ResMed","ROK":"Rockwell Automation","ROL":"Rollins",
    "ROP":"Roper Technologies","ROST":"Ross Stores","RSG":"Republic Services",
    "RTX":"RTX Corp","SBAC":"SBA Communications","SBUX":"Starbucks",
    "SCHW":"Charles Schwab","SHW":"Sherwin-Williams","SJM":"J.M. Smucker",
    "SLB":"SLB (Schlumberger)","SNA":"Snap-on","SNPS":"Synopsys",
    "SO":"Southern Company","SPG":"Simon Property","SPGI":"S&P Global",
    "SRE":"Sempra","STE":"Steris","STT":"State Street",
    "STX":"Seagate Technology","STZ":"Constellation Brands","SWK":"Stanley Black & Decker",
    "SWKS":"Skyworks Solutions","SYF":"Synchrony Financial","SYK":"Stryker",
    "SYY":"Sysco","T":"AT&T","TAP":"Molson Coors",
    "TDG":"TransDigm","TDY":"Teledyne Technologies","TECH":"Bio-Techne",
    "TEL":"TE Connectivity","TER":"Teradyne","TFC":"Truist Financial",
    "TFX":"Teleflex","TGT":"Target","TJX":"TJX Companies",
    "TMO":"Thermo Fisher","TMUS":"T-Mobile","TPR":"Tapestry",
    "TRGP":"Targa Resources","TRMB":"Trimble","TROW":"T. Rowe Price",
    "TRV":"Travelers","TSCO":"Tractor Supply","TSLA":"Tesla",
    "TSN":"Tyson Foods","TT":"Trane Technologies","TTWO":"Take-Two Interactive",
    "TXN":"Texas Instruments","TYL":"Tyler Technologies","UAL":"United Airlines",
    "UDR":"UDR Inc","UHS":"Universal Health Services","UNH":"UnitedHealth",
    "UNP":"Union Pacific","UPS":"UPS","URI":"United Rentals",
    "USB":"U.S. Bancorp","V":"Visa","VFC":"VF Corp",
    "VICI":"VICI Properties","VLO":"Valero Energy","VMC":"Vulcan Materials",
    "VNO":"Vornado Realty","VRSK":"Verisk Analytics","VRSN":"VeriSign",
    "VRTX":"Vertex Pharmaceuticals","VTR":"Ventas","VTRS":"Viatris",
    "VZ":"Verizon","WAB":"Wabtec","WAT":"Waters Corp",
    "WBA":"Walgreens Boots Alliance","WBD":"Warner Bros Discovery","WDC":"Western Digital",
    "WEC":"WEC Energy","WELL":"Welltower","WFC":"Wells Fargo",
    "WHR":"Whirlpool","WM":"Waste Management","WMB":"Williams Companies",
    "WMT":"Walmart","WRB":"W.R. Berkley","WRK":"WestRock",
    "WST":"West Pharmaceutical","WTW":"Willis Towers Watson","WY":"Weyerhaeuser",
    "WYNN":"Wynn Resorts","XEL":"Xcel Energy","XOM":"ExxonMobil",
    "XRAY":"Dentsply Sirona","XYL":"Xylem","YUM":"Yum! Brands",
    "ZBH":"Zimmer Biomet","ZBRA":"Zebra Technologies","ZION":"Zions Bancorporation",
    "ZTS":"Zoetis",
}

# Set for fast membership checks on the website filter
DJIA_SET = set(DJIA_TICKERS)
SP500_SET = set(SP500_TICKERS)
